### ISSUE TITLE
get_tags() method broken on dynamic_loading branch

### ISSUE THREAD

**Issue by ghost** [django-rdf-tools/django-coop#125]
<pre>
>>> o1=Organization.objects.all()[9]
>>> o1.get_tags()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/clo/projects/dj4coop/quinode-django-coop-8bde146/coop/org/models.py", line 362, in get_tags
    return self.tags.all()
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/manager.py", line 116, in all
    return self.get_query_set()
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/coop_tag/managers.py", line 160, in get_query_set
    return self.through.tags_for(self.model, self.instance)
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/coop_tag/models.py", line 121, in tags_for
    '%s__content_object' % cls.tag_relname(): instance
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/manager.py", line 143, in filter
    return self.get_query_set().filter(*args, **kwargs)
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/query.py", line 621, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/query.py", line 639, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    can_reuse=used_aliases, force_having=force_having)
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/sql/query.py", line 1122, in add_filter
    process_extras=process_extras)
  File "/home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/django/db/models/sql/query.py", line 1316, in setup_joins
    "Choices are: %s" % (name, ", ".join(names)))
FieldError: Cannot resolve keyword 'content_object' into field. Choices are: article, content_type, exchange, id, object_id, organization, person, tag
</pre>

bien sur, idem avec `o1.tags.all()`

Cela arrive dans le même environnement que l'issue #123, aussi bien django1.4 que la version de développement.
Dans la méthode `tags_for`, je ne comprends pas ce qui cloche.

<pre>
ipdb> up
> /home/clo/.virtualenvs/dj4c/lib/python2.6/site-packages/coop_tag/models.py(121)tags_for()
    120             return cls.tag_model().objects.filter(**{
--> 121                 '%s__content_object' % cls.tag_relname(): instance
    122             })

ipdb> cls.tag_model().objects
&lt;mptt.managers.TreeManager object at 0x2ed3b10&gt;
ipdb> cls.tag_relname()
'coop_local_taggeditem_items'
ipdb> model
&lt;class 'coop.base_models.Organization'&gt;
ipdb> instance
&lt;Organization: Access Equilibre&gt;
</pre>

j'ai essayé de changer le `cls.tag_relname` pour avoir organization, mais pas mieux. :-(

**Comment by domguard** [comment]
https://docs.djangoproject.com/en/dev/topics/db/managers/#custom-managers-and-model-inheritance
